#!/usr/bin/env ruby
$LOAD_PATH.unshift "#{File.dirname(__FILE__)}/lib"

require 'crypto'
require 'arcanum'
require 'sqlite3'
require 'csv'
require 'customization'


PASS_DIR = "#{ENV['HOME']}/.scribe/".freeze

##
# Check Operating System Info for OS Specific needs
##
def check_os
  # Enable and Configure OpenBSD OS Allowed System Calls and Filesystem Protections
  if RUBY_PLATFORM.include? 'openbsd'
    require 'pledge'
    require 'unveil'

    Pledge.unveil("#{ENV['HOME']}" => 'rwc')
    Pledge.pledge('rpath wpath cpath flock tty')
    $VERBOSE = nil # Pledge causes weirdness with SQLite3 gem, workaround to surpress encoding warning: warning: failed to load encoding (utf-16le); use ascii-8bit instead
  end
end

##
# Ensures folder and database has been created.
##
def start_up
  if !File.directory?(PASS_DIR)
    Dir.mkdir(PASS_DIR)
    vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"

    # Set up Password Database
    vault.execute <<-SQL
      CREATE TABLE IF NOT EXISTS passwords(
        site_name TEXT,
        username TEXT,
        password TEXT,
        date_modified TEXT
      );
    SQL
  end
end

##
# Insert New Entry into Database
##
def insert_into_db(site_name, username, password, method)
  vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"
  if method == 'args'  
    vault.execute 'INSERT INTO passwords (site_name, username, password, date_modified) VALUES (?, ?, ?, ?)', site_name, username, Crypto::encrypt_line(password), Time.now.strftime('%m/%d/%Y')
    puts "Added #{site_name} information successfully!".success.bold
  else
    puts 'Enter Username:'.bold.prompt
    username = $stdin.gets.chomp
    puts 'Enter Password:'.bold.prompt
    password = $stdin.noecho(&:gets).chomp
    vault.execute 'INSERT INTO passwords (site_name, username, password, date_modified) VALUES (?, ?, ?, ?)', site_name, username, Crypto::encrypt_line(password), Time.now.strftime('%m/%d/%Y')
    puts "Added #{site_name} information successfully!".success.bold
  end  
end

##
# Delete Entry from Database.
##
def delete_from_db(query)
  check_value(query, "Site")
  
  vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"
  vault.results_as_hash = true

  results = vault.execute 'SELECT * FROM passwords WHERE site_name = ?', query
  if results.empty?
    puts 'No Results Found!'.error.bold
  else
    vault.execute 'DELETE FROM passwords WHERE site_name = ?', query
    puts "Deleted #{query} successfully!".success.bold
  end
end

##
# Modify Entry from Database
##
def modify_password(site_name, username, password)
  vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"
  
  results = vault.execute 'SELECT * FROM passwords WHERE site_name = ?', site_name
  if results.empty?
    puts 'Site name does not exist!'.error.bold
  else
    vault.execute 'UPDATE passwords SET username = ?, password = ?, date_modified = ? WHERE site_name = ?', username, Crypto::encrypt_line(password), Time.now.strftime('%m/%d/%Y'), site_name
    puts "Modified #{site_name} information successfully!".success.bold
  end
end

##
# Query Database by Site Name
##
def query_db(query)
  check_value(query, "Site")

  vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"
  vault.results_as_hash = true
  if query == 'all'
    results = vault.execute 'SELECT * from passwords'
  else
    results = vault.execute 'SELECT * FROM passwords WHERE site_name = ?', query
  end

  if results.empty?
    puts 'No Results Found!'.error.bold
  else
    output_results(results);
  end
end

##
# Purge Database
##
def purge_db
  vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"
  vault.execute 'DELETE FROM passwords'
  puts 'Deleted Password Vault!'.success.bold
end

##
# Exports Passwords into a CSV.
##
def export_passwords 
  vault = SQLite3::Database.open "#{PASS_DIR}/vault.db"
  vault.results_as_hash = true
  results = vault.execute 'SELECT * from passwords'

  if results.empty?
    puts 'No Passwords to Export!'.error.bold
  else
    decrypted_password = Crypto.get_password('Enter Decryption Password')
    cur_time = Time.now.strftime('%m%d%y')
    export_file_name = "#{ENV['HOME']}/Scribe_Password_#{cur_time}.csv"
  
    file = File.new(export_file_name, 'w')
    file.puts('site_name,username,password')
    results.each do |row|
      plain_text_password = Crypto.decrypt_line(row['password'], decrypted_password)
      file.puts("#{row['site_name']},#{row['username']},#{plain_text_password}")
      plain_text_password.clear
    end
  end
  puts "Exported! File is named: #{export_file_name}!".success.bold
  puts 'Warning! Passwords are in PLAIN TEXT for Scribe Importation!'.info.bold
end

##
# Output Results from Query
##
def output_results(results)
  decrypted_password = Crypto.get_password('Enter Decryption Password')
  results.each do |row|
    plain_text_password = Crypto.decrypt_line(row['password'], decrypted_password)
    puts "Site Name: #{row['site_name']}".info.bold
    puts "Username: #{row['username']}".success
    puts "Password: #{plain_text_password}".success
    puts "Date Modified: #{row['date_modified']}".success
    puts ''
    plain_text_password.clear
  end
end

##
# Import Passwords from CSV.
##
def import_passwords(file_location)
  check_value(file_location, "File Location")

  encryption_password = Crypto.get_password('Enter Password to Encrypt Imported Passwords')
  CSV.foreach(file_location, headers: true) do |row|
    insert_into_db(row['site_name'], row['username'], row['password'], encryption_password)
  end
  puts 'Importation Done!'.success.bold
end

##
# Handle Arguments
##
def decisions(arg_array)
  case arg_array[0]
  when 'get'
    query_db(arg_array[1])
  when 'add'
    if(arg_array.length < 4)
      insert_into_db(arg_array[1], arg_array[2], arg_array[3], 'manual')
    else
      insert_into_db(arg_array[1], arg_array[2], arg_array[3], 'args')
    end
  when 'remove'
    delete_from_db(arg_array[1])
  when 'purge'
    purge_db
  when 'import'
    import_passwords(arg_array[1])
  when 'export'
    export_passwords
  when 'gen'
    Crypto.gen_password(arg_array[1])
  when 'help'
    usage
  when 'about'
    about
  when 'update'
    modify_password(arg_array[1], arg_array[2], arg_array[3])
  when 'create_arcanum'
    Arcanum.mount_secure_folder("#{PASS_DIR}#{arg_array[1]}")
  when 'mount_arcanum'
    Arcanum.mount_secure_folder("#{PASS_DIR}#{arg_array[1]}")
  when 'unmount_arcanum'
    Arcanum.unmount_secure_folder("#{PASS_DIR}#{arg_array[1]}")
  when 'destroy_arcanum'
    Arcanum.destroy_arcanum("#{PASS_DIR}#{arg_array[1]}")
    puts "Arcanum Destroyed!".success.bold
  else
    puts 'ERROR: Not a command! Check out help: scribe help'.error.bold
    exit(1)
  end
end

##
# Checks Value for Nil, used for site names, file location.
##
def check_value(value, type)
  if(value == nil)
    puts "No #{type} Given!".error.bold
    exit(1)
  end
end

##
# Usage
##
def usage
  puts 'scribe [arg1 ... arg4]'
  puts 'Args:'
  puts 'add <site> <username> <password>         Add Site to Password Vault'
  puts 'add <site>                               Same as above, but will prompt for username and password'
  puts 'remove <site_name>                       Remove Site from Password Vault'
  puts 'get <site_name>                          Get Site info from Password Vault'
  puts 'purge                                    Delete Password Vault'
  puts 'import <file name>                       Import CSV file of passwords'
  puts 'export                                   Export CSV file of Password Vault'
  puts 'gen <num of characters>                  Generates a SecureRandom Base64 Password. Default 15.'
  puts 'create_arcanum <folder_name>             Create a CryFS encrypted Folder'
  puts 'mount_arcanum <folder_name>              Mount encrypted Folder'
  puts 'unmount_arcanum <folder_name>            Unmount encrypted Folder'
  puts 'destroy_arcanum <folder_name>            Destroy encrypted Folder'
  puts 'help                                     Display this help'
  puts 'about                                    Display about page'
end

##
# About
##
def about
  puts 'Scribe: A CLI Password Manager'.info.bold
  puts 'Version 1.1'.info
  puts 'Written by James Gillman'.info
end

# Main Function
##
def main
  check_os
  arg_array = ARGV
  start_up
  decisions(arg_array)
  exit(0)
end

main